const {test}=require('node:test'),a=require('node:assert/strict'),C=require('../CampusAssistant/Web/core.js');
require('../CampusAssistant/Web/calendar-data.js');
const data=globalThis.CampusCalendarData;
function timetable(q=3,description='ZZ9999 示例课程【3Q】 2単位',day=5){return '学生番号 | DEMO0000\n年度・学期 | 2026年度 '+q+'クォーター\n| 月曜日 | 火曜日 | 水曜日 | 木曜日 | 金曜日 | 土曜日\n'+[1,2,3,4,5,6].map(p=>p+'限\n'+[1,2,3,4,5,6].map(d=>p===1&&d===day?description:'未登録').join('\n')).join('\n')+'\n集中講義など\n登録されていません\n件数 | 1件';}
test('profile rejects missing and ambiguous identity',()=>{a.equal(C.profile('学生番号 | DEMO0000\n学生氏名 | 示例同学').student,'DEMO0000');a.throws(()=>C.identity('学生番号 | DEMO0000\n学生番号 | DEMO1111'));a.throws(()=>C.profile('password field'));});
test('quarter parser validates full table and count',()=>{const t=C.parse(timetable());a.equal(t.quarter,3);a.equal(t.lessons[0].day,5);a.throws(()=>C.parse(timetable().replace('件数 | 1件','件数 | 2件')));a.throws(()=>C.parse(timetable().replace('6限','7限')));});
test('status timetable never invents enrollment availability',()=>{const r=C.readOnlyRegistration(timetable(),'DEMO0000');a.equal(r.rows[0].available,false);a.throws(()=>C.readOnlyRegistration(timetable(),'OTHER0000'));});
test('grade total and pass status verified',()=>{const s='No. | 科目大区分 | other\n1 | A | B | C | Example | 2 | 2026 | Q1 | 80 | A | 合\n\n修得単位数 | 2\n年度・学期 | 学期GPA | 年間GPA | 通算GPA\n2026 | 3 | 3 | 3.5';a.equal(C.parse(s).earned,2);a.equal(C.parse(s).gpa,3.5);a.throws(()=>C.parse(s.replace('修得単位数 | 2','修得単位数 | 4')));a.throws(()=>C.parse(s.replace('80','40')));});
test('online value distinguished from blended and offline',()=>{a.equal(C.delivery('オンライン授業（リアルタイム配信型） / on-line course (real time)'),'线上授课（实时）');a.equal(C.delivery('対面授業 / face-to-face'),'线下授课');a.equal(C.delivery('blended'),'混合授课');a.equal(C.venue(2026,'KB4012','online'),'按每次授课通知确认');});
test('course selections retain stable IDs across modal and refresh',()=>{const r={student:'DEMO',scope:'Q3',at:100,rows:[{id:'one',available:true},{id:'two',available:true}]};a.deepEqual(C.reconcile(r,structuredClone(r),['two']),['two']);a.deepEqual(C.reconcile(r,{...r,scope:'Q4'},['two']),[]);a.equal(C.selectedRows(r,['two'],101)[0].id,'two');a.throws(()=>C.selectedRows(r,['two','two'],101));a.throws(()=>C.selectedRows(r,['one'],400000));a.throws(()=>C.selectedRows(r,['one'],0));});
test('schedule day period pairs and ranges remain paired',()=>{a.deepEqual(C.slots('月１・２、金３'),[{day:1,period:1},{day:1,period:2},{day:5,period:3}]);a.deepEqual(C.slots('火曜日2〜3'),[{day:2,period:2},{day:2,period:3}]);a.deepEqual(C.slots('月10'),[]);a.equal(C.slots('金1')[0].day,5);});
test('calendar navigation crosses term and calendar year coherently',()=>{a.equal(C.termOn(C.shift(C.monday('2026-09-17'),7)),'2026 · Q3');a.equal(C.termOn('2027-01-06'),'2026 · Q4');a.equal(C.termOn('2028-01-01'),null);a.equal(C.shift('2026-12-31',1),'2027-01-01');});
test('all saved quarters resolve together without active-quarter filter',()=>{const q3=C.parse(timetable(3,'ZZ9999 示例【3Q】 2単位')),q4=C.parse(timetable(4,'ZZ9998 示例【4Q】 2単位'));const d={...data,offerings:{ZZ9999:{term:'3Q',campus:'MITO'},ZZ9998:{term:'4Q',campus:'MITO'}}};const r=C.events({q3,q4},d);a.equal(r.events.length,14);a.ok(r.events.some(e=>e.date==='2026-09-25'));a.ok(r.events.some(e=>e.date==='2027-01-29'));});
test('unknown years and irregular courses do not generate fictional dates',()=>{const t=C.parse(timetable());a.equal(C.events({t:{...t,year:2028}},data).events.length,0);a.equal(C.events({t},{...data,offerings:{ZZ9999:{term:'3Q',campus:'MITO',irregular:true}}}).events.length,0);});
test('semester exceptions and dedup use verified dates',()=>{const t=C.parse(timetable(4,'ZZ9999 示例【後期】 2単位',1)),d={...data,offerings:{ZZ9999:{term:'後期',campus:'MITO'}}};const r=C.events({a:t,b:{...t,at:100}},d);a.equal(r.events.length,7);a.ok(r.events.some(e=>e.date==='2027-01-06'));});
test('academic notifications compare same owner and nonempty GPA',()=>{a.deepEqual(C.changes({student:'A',earned:10,gpa:3},{student:'A',earned:12,gpa:3.2}),['已修学分 10 → 12','GPA 3 → 3.2']);a.deepEqual(C.changes({student:'A',earned:10,gpa:3},{student:'B',earned:12,gpa:4}),[]);a.deepEqual(C.changes({student:'A',earned:10,gpa:null},{student:'A',earned:10,gpa:3}),[]);});
