'use strict';
let forecastYear=2026,forecastPeriod=5;
const A=CampusAcademic,AD=CampusAcademicData;
function currentScope(){return state.curriculum||A.scope(state.profile,AD);}
// A graduation minimum is distinct from a registration cap.
function creditAmount(earned,required){return required>0?`${earned} / ${required}`:`已修 ${earned} 学分`;}
function renderCreditTree(nodes){return nodes.map(n=>`<div class="credit-node"><div class="row spread"><strong>${h(n.label)}</strong><span>${creditAmount(n.earned,n.required)}</span></div>${n.required>0?`<progress value="${Math.min(n.earned,n.required)}" max="${n.required}"></progress><p class="small">还需 ${n.remaining} 学分${n.added?' · 预计新增 '+n.added+' · 通过后还需 '+n.projectedRemaining:''}</p>`:`<p class="small">预计新增 +${n.added||0}</p>`}${renderCreditTree(n.children)}</div>`).join('');}
function renderConstraints(rule){
 const rules=rule?.constraints||[];
 return rules.length?`<section class="card"><h2>选课规则</h2><p>适用：${h([rule.cohort,rule.faculty,rule.department,rule.program].filter(Boolean).join(' · '))}</p><p class="small">分母为毕业最低要求，选课上限与必修组合分别核对。</p><details><summary>按已同步成绩核对必修</summary>${typeof preview!=='undefined'&&preview?'<p class="small">虚构预览只提供大学入門ゼミ 2 学分；其余零值不是你的真实成绩。</p>':''}<p>仅计已合格、分类明确的成绩；预计新增不计入。学分满足不代表审批等条件已满足。</p>${A.constraintChecks(currentScope(),state.snapshots.grades?.rows??null,AD).map(c=>`<p>${h(c.title)}：${c.status==='尚未同步'?'—':c.earned}/${c.minimum} · ${h(c.status)}<br><span class="small">${h(c.note)}</span></p>`).join("")}</details>${rules.map(r=>`<details><summary>${h(r.title)}</summary><p>${h(r.scope)}</p>${r.limit!==null?`<p>上限：${r.limit} ${h(r.unit)}</p>`:''}<p>${h(r.detail)}</p><a href="${h(r.source)}" target="_blank" rel="noopener">学校原文 · ${h(r.page)} 页</a></details>`).join('')}</section>`:'';
}
function showAcademic(){
 const grade=state.snapshots.grades,scope=currentScope(),rule=A.rule(scope,AD),quarters=forecastPeriod===4?[1,2]:forecastPeriod===5?[3,4]:[forecastPeriod+1],f=grade?A.forecast(grade,state.snapshots,forecastYear,quarters,D,scope?.faculty,AD):null,progress=grade&&scope?A.progress(scope,grade.rows,AD,f?.courses||[]):null;
 const panel=document.createElement('div');panel.id='academic-panel';
 const options=['Q1','Q2','Q3','Q4','前期 Q1+Q2','后期 Q3+Q4'];
 const tree=renderCreditTree;
 panel.innerHTML=`<section class="card"><h2>学分预览</h2><div class="row"><label>学年度 <input id="forecast-year" type="number" min="1900" max="2099" value="${forecastYear}"></label><select id="forecast-period" aria-label="预览学期">${options.map((x,i)=>`<option value="${i}" ${i===forecastPeriod?'selected':''}>${x}</option>`).join('')}</select></div>${f?`<div class="stats"><div class="stat"><div class="number">${f.offered}</div><p>本期可获得学分</p></div><div class="stat"><div class="number">${f.total}</div><p>预计总学分</p></div></div><p>已修 ${f.earned} + 预计新增 ${f.added} = ${f.total}</p><p class="small">跨学季课程仅计一次；待出成绩课程全部合格时的预估，以学校认定为准。</p>${f.missing.length?'<p class="warning">尚缺 '+f.missing.map(q=>'Q'+q).join('、')+' 课表，仅预览已有课程。</p>':''}<details><summary>课程明细 · ${f.courses.length}</summary>${f.courses.map(c=>`<p>${h(c.name)} · ${c.credits} 学分 · ${c.quarter?'Q'+c.quarter:'结束学季待核对'}<br><span class="small">${h(c.state)}</span></p>`).join('')}</details>`:'<p>同步学校成绩与课表后显示学分预览。</p>'}</section><section class="card"><h2>毕业规则</h2><p>${h(scope?[scope.faculty,scope.department,scope.program,scope.cohort].filter(Boolean).join(' · '):'学校学籍尚未读取')}</p><p class="small">${state.curriculum?'使用自行选择的规则':'根据学校学籍匹配'}；按要件年度匹配，不用当前年级倒推。</p><button id="select-curriculum">选择适用规则</button>${rule?'<button id="rule-source" class="secondary">查看学校履修要项</button>':''}<button id="evidence" class="secondary">补充履修要项 PDF</button><p class="small">补充文件只保存在本机，不自动用于计算。</p><p>${h(rule?.detail||'毕业要求待核对，学校成绩正常保留。')}</p>${progress?tree(progress.nodes)+`<p>已修待分类：${progress.unassigned} 学分；预计新增待分类：${progress.plannedUnassigned} 学分。</p><p class="small">待分类学分不擅自填入毕业类别。类别最低学分、必修课程、实习及其他条件须同时满足。</p><details><summary>课程分类明细</summary>${progress.courses.map(c=>`<p>${h(c.name)} · ${c.credits} · ${h(c.c.label)}</p>`).join('')}</details>`:rule?.requirements.length?'<p>同步成绩后计算各类别还需的学分。</p>':''}</section>${renderConstraints(rule)}`;
 $('content').prepend(panel);panel.querySelectorAll('a').forEach(a=>a.onclick=e=>{e.preventDefault();bridge('openExternal',{url:a.href}).catch(e=>toast(e.message));});
 $('forecast-year').onchange=e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=1900&&v<=2099){forecastYear=v;render();}};
 $('forecast-period').onchange=e=>{forecastPeriod=Number(e.target.value);render();};$('select-curriculum').onclick=selectCurriculum;
 if(rule)$('rule-source').onclick=()=>bridge('openExternal',{url:rule.guide}).catch(e=>toast(e.message));
 $('evidence').onclick=()=>scope?bridge('importEvidence',{scope:JSON.stringify(scope)}).then(()=>toast('文件已保存到本机，尚未用于计算。')).catch(e=>toast(e.message)):toast('请先选择适用规则');

 const manual=document.createElement('section');manual.className='card';manual.innerHTML='<h2>本机成绩试算</h2><p>2026 工学部 情報工学科规则；手工记录与学校同步成绩分开保存。</p><button id="manual-records">管理手工成绩与 GPA</button>';panel.append(manual);$('manual-records').onclick=manualRecords;
}
function selectCurriculum(){
 const current=currentScope()||{},faculties=[...new Set(AD.curricula.map(r=>r.faculty))];
 modal('选择适用规则','<p>按学校要件年度选择，不用年级倒推。自行选择不会修改学校资料。</p><label>学部／学環<select id="scope-faculty"></select></label><label>学科／課程<select id="scope-department"></select></label><label>规则年度<select id="scope-cohort"><option>2024</option><option>2025</option><option>2026</option></select></label><label>コース／プログラム<select id="scope-program"></select></label>',[['学校匹配',async()=>{state.curriculum=null;await persist();render();}],['取消',()=>{}],['保存',async()=>{state.curriculum={faculty:$('scope-faculty').value,department:$('scope-department').value,cohort:Number($('scope-cohort').value),program:$('scope-program').value};await persist();render();}]]);
 const fill=(id,values,value)=>{$(id).innerHTML=values.map(v=>`<option value="${h(v)}">${h(v||'—')}</option>`).join('');if(values.includes(value))$(id).value=value;};
 fill('scope-faculty',faculties,current.faculty);$('scope-cohort').value=String(current.cohort||2026);
 const programs=()=>fill('scope-program',[...new Set(AD.curricula.filter(r=>r.faculty===$('scope-faculty').value&&r.department===$('scope-department').value&&r.cohort===Number($('scope-cohort').value)).map(r=>r.program))],current.program);
 const departments=()=>{fill('scope-department',[...new Set(AD.curricula.filter(r=>r.faculty===$('scope-faculty').value).map(r=>r.department))],current.department);programs();};departments();$('scope-faculty').onchange=departments;$('scope-department').onchange=programs;$('scope-cohort').onchange=programs;
}
function editPersonal(entry=null){modal(entry?'编辑个人安排':'添加个人安排',`<label>标题<input id="edit-name" type="text" maxlength="100" value="${h(entry?.name||'')}"></label><label>日期<input id="edit-date" type="date" value="${h(entry?.date||date)}"></label><label>节次<select id="edit-period">${[1,2,3,4,5,6].map(p=>`<option ${p===entry?.period?'selected':''}>${p}</option>`).join('')}</select></label>`,[['取消',()=>{}],...(entry?[['删除',async()=>{state.personal=state.personal.filter(e=>e.id!==entry.id);await persist();render();}]]:[]),['保存',async()=>{const name=$('edit-name').value.trim(),day=$('edit-date').value;if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(day))return toast('请填写标题和日期');const item={id:entry?.id||'personal-'+Date.now(),name,date:day,period:Number($('edit-period').value),personal:true};state.personal=state.personal.filter(e=>e.id!==item.id).concat(item);await persist();render();}]]);}
function enhanceCalendar(){
 $('add-event').onclick=()=>editPersonal();const controls=$('add-event').parentElement;
 const share=document.createElement('button');share.textContent='导出日历';share.onclick=()=>bridge('shareCalendar',{text:A.ics(allEvents().events)}).catch(e=>toast(e.message));controls.append(share);
 const personal=state.personal.filter(e=>e.date===date);if(personal.length){const box=document.createElement('section');box.className='card';box.innerHTML='<h3>个人安排 · '+h(date)+'</h3>'+personal.map(e=>`<button class="edit-personal" data-id="${h(e.id)}">${h(e.name)} · 编辑</button>`).join('');$('content').append(box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>editPersonal(personal.find(e=>e.id===b.dataset.id)));}
}
function enhanceSettings(){const box=document.createElement('section');box.className='card';box.innerHTML='<h2>主题</h2><button id="theme-settings">主题与美化包</button><h2>语言 / Language / 言語</h2><select id="language"><option value="zh">中文</option><option value="ja">日本語</option><option value="en">English</option><option value="ko">한국어</option></select><h3>通知偏好</h3><label><input id="academic-alert" type="checkbox"> 学分、GPA 与选课通知</label><p>YIN · <button id="contact">snai2514@gmail.com</button></p>'; $('content').append(box);$('theme-settings').onclick=themeSettings;$('language').value=state.language||'zh';$('language').onchange=async e=>{state.language=e.target.value;await persist();render();};$('academic-alert').checked=state.alerts!==false;$('academic-alert').onchange=async e=>{state.alerts=e.target.checked;await persist();};$('contact').onclick=()=>bridge('openExternal',{url:'mailto:snai2514@gmail.com'}).catch(e=>toast(e.message));}
function localize(){const language=state.language||'zh';if(language==='zh')return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){if(['SCRIPT','STYLE','OPTION'].includes(n.parentElement?.tagName))continue;const original=n.textContent.trim(),translated=CampusLanguages[original]?.[language];if(translated)n.textContent=n.textContent.replace(original,translated);}}
function manualRecords(){
 const records=state.manualRecords||[],s={faculty:'工学部',department:'情報工学科',cohort:2026,program:''},r=A.rule(s,AD),gpa=A.manualGpa(records),earned=records.filter(r=>r.kind==='SCORED'?r.score>=60:['RECOGNIZED','INTERNSHIP'].includes(r.kind));
 const leaf=A.leaves(r.requirements),count=id=>earned.filter(r=>r.category===id).reduce((sum,r)=>sum+r.credits,0);
 modal('本机成绩与 GPA',`<p>本机计算 GPA：${gpa??'—'}。非学校官方同步值。</p><p class="small">GP =（分数 − 55）÷ 10；低于 60 分按 0，不及格仍计入分母。认定、实习、要求外、取消履修和在修记录不计 GPA。</p><details><summary>各类学分缺口</summary>${leaf.map(n=>`<p>${h(n.label)}：${creditAmount(count(n.id),n.required)}${n.required>0?" · 还需 "+Math.max(0,n.required-count(n.id)):""}</p>`).join('')}</details>${records.map(r=>`<button class="manual-edit" data-id="${h(r.id)}">${h(r.name)} · ${r.credits} 学分</button>`).join('')}`,[['关闭',()=>{}],['添加成绩',()=>editManual()]]);document.querySelectorAll('.manual-edit').forEach(b=>b.onclick=()=>editManual(records.find(r=>r.id===b.dataset.id)));
}
function editManual(original=null,draft=original){const r=A.rule({faculty:'工学部',department:'情報工学科',cohort:2026,program:''},AD),kinds={SCORED:'百分制成绩',RECOGNIZED:'认定学分',INTERNSHIP:'学外实习',OUTSIDE:'毕业要求外',WITHDRAWN:'已获准取消履修',PENDING:'在修／成绩待定'};modal('编辑手工成绩',`<label>课程代码<input id="manual-id" type="text" maxlength="100" value="${h(draft?.id||'')}"></label><label>课程名称<input id="manual-name" type="text" maxlength="100" value="${h(draft?.name||'')}"></label><label>学分<input id="manual-credits" type="number" min="0.1" max="100" step="0.1" value="${draft?.credits||2}"></label><label>类型<select id="manual-kind">${Object.entries(kinds).map(([id,name])=>`<option value="${id}" ${id===draft?.kind?'selected':''}>${name}</option>`).join('')}</select></label><label>分数<input id="manual-score" type="number" min="0" max="100" value="${draft?.score??''}"></label><label>分类<select id="manual-category"><option value="">待分类</option>${A.leaves(r.requirements).map(n=>`<option value="${n.id}" ${n.id===draft?.category?'selected':''}>${h(n.label)}</option>`).join('')}</select></label>`,[['取消',manualRecords],...(original?[['删除',async()=>{state.manualRecords=state.manualRecords.filter(r=>r.id!==original.id);await persist();manualRecords();}]]:[]),['保存',async()=>{const record={id:$('manual-id').value.trim(),name:$('manual-name').value.trim(),credits:Number($('manual-credits').value),kind:$('manual-kind').value,score:$('manual-score').value===''?null:Number($('manual-score').value),category:$('manual-category').value},next=(state.manualRecords||[]).filter(r=>r.id!==original?.id).concat(record);try{A.manualGpa(next);}catch(e){toast(e.message);return editManual(original,record);}state.manualRecords=next;await persist();manualRecords();}]]);}
