(function(root){
 'use strict';
 const norm=s=>String(s||'').normalize('NFKC').replace(/\s+/g,'').replace(/(?<=[ァ-ヶ])[-−](?=[ァ-ヶ])/g,'ー');
 const name=s=>norm(String(s).split('【')[0]);
 const leaves=nodes=>nodes.flatMap(n=>n.children.length?leaves(n.children):[n]);
 const quarter=t=>{const s=String(t).normalize('NFKC');return Number(s.match(/([1-4])クォーター/)?.[1])||({'前期':2,'後期':4,'后期':4}[s.trim()])||null;};
 const termQuarter=t=>({'前期':2,'前学期':2,'後期':4,'後学期':4,'通年':4}[t])||Number(String(t).match(/^([1-4])Q$/)?.[1])||null;
 function scope(profile,data){if(!profile)return null;const faculty=profile.affiliation.match(/^(.+?(?:学部|学環))/)?.[1]||'',tail=profile.affiliation.slice(faculty.length).trim(),deps=[...new Set(data.curricula.filter(s=>s.faculty===faculty).map(s=>s.department))],department=deps.sort((a,b)=>b.length-a.length).find(s=>tail.startsWith(s))||(faculty==='地域未来共創学環'?faculty:'');return {faculty,department,cohort:profile.curriculumYear,program:profile.program||tail.slice(department.length).trim()};}
 function rule(scope,data){return scope&&data.curricula.find(r=>['faculty','department','cohort','program'].every(k=>r[k]===scope[k]));}
 function science(l,q,faculty,data){if(faculty!=='理学部')return null;const terms=[...new Set(data.science.filter(r=>r[0]===name(l.name)&&Number(r[1])===l.credits&&Number(r[2])===l.day&&Number(r[3])===l.period&&(r[4]===q+'Q'||r[4]===(q<=2?'前期':'後期'))).map(r=>r[4]))];return terms.length===1?{term:terms[0],campus:'MITO'}:null;}
 function forecast(grade,snapshots,year,quarters,calendar,faculty,data){
  const tables=Object.values(snapshots).filter(t=>t.lessons&&t.year===year&&t.student===grade.student),present=new Set(tables.map(t=>t.quarter)),groups=new Map();
  for(const t of tables)for(const l of t.lessons){const explicit=termQuarter(l.name.match(/【(前期|前学期|後期|後学期|通年|[1-4]Q)】/)?.[1]),key=JSON.stringify([l.code,Math.floor((t.quarter-1)/2),explicit]);groups.set(key,[...(groups.get(key)||[]),{l,q:t.quarter,explicit}]);}
  const candidates=[];
  for(const meetings of groups.values()){
   const {l,explicit}=meetings[0],observed=[...new Set(meetings.map(m=>m.q))],variants=new Set(meetings.map(m=>m.l.description||m.l.name+' '+m.l.credits)),matching=grade.rows.filter(g=>Number(g.year)===year&&name(g.name)===name(l.name)&&g.credits===l.credits&&observed.includes(quarter(g.term))),resultQ=[...new Set(matching.map(g=>quarter(g.term)).filter(Boolean))],scienceQ=[...new Set(meetings.map(m=>termQuarter(science(m.l,m.q,faculty,data)?.term)).filter(Boolean))];
   const end=year===2026?(termQuarter(calendar.offerings[l.code]?.term)||(scienceQ.length===1?scienceQ[0]:null)):null,ends=explicit?[explicit]:resultQ.length?resultQ:[end&&Math.floor((end-1)/2)===Math.floor((observed[0]-1)/2)?end:null];
   for(const q of ends)candidates.push({code:l.code,name:l.name.split('【')[0].trim(),credits:l.credits,quarter:q,observed,state:variants.size!==1||!(l.credits>0)||q===null?'待核对，不计预览':'预计新增'});
  }
  const courses=candidates.map(c=>{if(c.state!=='预计新增')return c;const matches=grade.rows.filter(g=>Number(g.year)===year&&quarter(g.term)===c.quarter&&name(g.name)===name(c.name)&&g.credits===c.credits),peers=candidates.filter(p=>name(p.name)===name(c.name)&&p.quarter===c.quarter&&p.credits===c.credits).length;return {...c,state:!matches.length?'预计新增':matches.length!==peers||new Set(matches.map(m=>m.passed)).size!==1?'成绩对应待核对，不计预览':matches[0].passed?'已修得，不重复增加':'不合格，不计新增'};}).filter(c=>quarters.includes(c.quarter)||(c.quarter===null&&c.observed.some(q=>quarters.includes(q))));
  const sum=states=>courses.filter(c=>states.includes(c.state)).reduce((n,c)=>n+c.credits,0),earned=grade.rows.filter(g=>g.passed).reduce((n,g)=>n+g.credits,0),added=sum(['预计新增']);return {courses,earned,added,total:earned+added,offered:sum(['预计新增','已修得，不重复增加']),completed:sum(['已修得，不重复增加']),failed:sum(['不合格，不计新增']),missing:quarters.filter(q=>!present.has(q))};
 }
 function target(scope,r,category){const all=leaves(r.requirements),n=norm(category);let match=all.filter(x=>x.id===category||norm(x.label)===n);if(match.length===1)return match[0];let alias=null;
  if(scope.faculty==='工学部')alias=({'学部共通専門基礎教育科目':'専門必修','学部共通専門基礎科目':'専門必修','必修':'専門必修','専門必修科目':'専門必修','学科共通専門基礎科目-必修':'専門必修','選択必修':'専門選択必修','選択必修科目':'専門選択必修','専門選択必修科目':'専門選択必修','学科共通専門基礎科目-選択必修':'専門選択必修'})[n];
  if(scope.faculty==='理学部')alias=({'基礎科目':'専門基礎科目','標準科目':scope.program==='生物科学コース'?'専門標準・発展科目':'専門標準科目','発展科目':scope.program==='生物科学コース'?'専門標準・発展科目':'専門発展科目','標準・発展科目':'専門標準・発展科目'})[n];
  match=all.filter(x=>x.label===alias);if(match.length===1)return match[0];
  if(['教育学部','農学部','地域未来共創学環'].includes(scope.faculty)&&['専門科目','教科に関する科目','教育の基礎的理解に関する科目','養護に関する科目','教育実践に関する科目','卒業研究','学環基盤科目','プログラム共通科目','プログラムコア科目','課題探究科目','コーオプ実習'].includes(n))return all.find(x=>x.label==='専門科目');
  if(scope.faculty==='理学部'&&['総合理学コース','学際理学コース'].includes(scope.program)&&['基礎科目','標準科目','発展科目','標準・発展科目'].includes(n))return all.find(x=>x.label==='専門科目');
  if(['自由履修科目','自由履修'].includes(n))return all.find(x=>x.id==='free'||x.label.startsWith('自由履修'));return null;
 }
 let indexedData=null,index=null;
 function catalog(scope,course,data){if(indexedData!==data){index=new Map();const strings=data.catalog.strings;for(const ids of data.catalog.rows){const r=ids.map(i=>strings[i]),key=norm(r[4]);index.set(key,[...(index.get(key)||[]),r]);}indexedData=data;}
  let rows=(index.get(norm(course.name))||[]).filter(r=>Number(r[0])===scope.cohort&&r[1]===scope.faculty&&(r[2]==='*'||r[2]===scope.department)&&(r[3]==='*'||r[3]===scope.program)&&(!r[9]||course.credits==null||Number(r[9])===course.credits));if(course.code){const exact=rows.filter(r=>r[8]?.toLowerCase()===course.code.toLowerCase());rows=exact.length?exact:rows.filter(r=>!r[8]);}return rows;
 }
 function classify(scope,course,data){const r=rule(scope,data),unknown={id:null,label:'待分类',excluded:false};if(!r?.requirements.length)return unknown;const path=String(course.category||'').split(/\s*\/\s*/).map(norm);if(path.some(p=>['卒業要件外','卒業要件外科目','卒業要件に算入しない科目'].includes(p)))return {...unknown,label:'毕业要求外',excluded:true};
  const result=(node,source)=>({id:node.id,label:node.label,source,excluded:false});for(const p of [...path].reverse()){const t=target(scope,r,p);if(t)return result(t,'学校成绩分类');}
  const rows=catalog(scope,course,data);if(rows.length&&rows.every(x=>x[5]==='outside'))return {...unknown,label:'毕业要求外',excluded:true};const matches=[...new Map(rows.map(x=>target(scope,r,x[5])).filter(Boolean).map(x=>[x.id,x])).values()];if(matches.length===1&&!rows.some(x=>x[5]==='outside'))return result(matches[0],rows[0][6]+'#page='+rows[0][7]);
  const ids=Object.entries(data.general).filter(([id,names])=>names.some(n=>norm(n)===norm(course.name)||path.includes(norm(n)))).map(([id])=>id),general=ids.length===1?ids[0]:/^(?:IntegratedEnglish[1-3][ABCD]|CommunicativeEnglish[1-3][AB])$/.test(norm(course.name))?'english':null;
  if(general&&!path.some(p=>p.includes('専門')||p.includes('自由履修'))){const n=leaves(r.requirements).find(x=>r.detailed?x.id===general:x.label==='基盤教育科目');if(n)return result(n,'大学共通教育履修案内');}return unknown;
 }
 function progress(scope,grades,data,projected=[]){const r=rule(scope,data);if(!r?.requirements.length)return null;const courses=grades.filter(g=>g.passed).map(g=>({...g,c:classify(scope,g,data)})),planned=projected.filter(g=>g.state==='预计新增').map(g=>{const direct=classify(scope,g,data),previous=[...new Map(grades.filter(p=>p.category&&norm(p.name)===norm(g.name)&&p.credits===g.credits).map(p=>classify(scope,p,data)).filter(c=>c.id||c.excluded).map(c=>[c.id+'/'+c.excluded,c])).values()];return {...g,c:previous.length===0?direct:previous.length===1?previous[0]:{id:null,excluded:false}};});
  function node(n){const children=n.children.map(node),earned=children.length?children.reduce((s,c)=>s+c.earned,0):courses.filter(c=>!c.c.excluded&&c.c.id===n.id).reduce((s,c)=>s+c.credits,0),added=children.length?children.reduce((s,c)=>s+c.added,0):planned.filter(c=>!c.c.excluded&&c.c.id===n.id).reduce((s,c)=>s+c.credits,0);return {...n,children,earned,added,remaining:Math.max(0,n.required-earned),projectedRemaining:Math.max(0,n.required-earned-added)};}
  return {nodes:r.requirements.map(node),unassigned:courses.filter(c=>!c.c.excluded&&!c.c.id).reduce((s,c)=>s+c.credits,0),plannedUnassigned:planned.filter(c=>!c.c.excluded&&!c.c.id).reduce((s,c)=>s+c.credits,0),courses};
 }
 function ics(events){const escape=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),times=[['084000','102500'],['103500','122000'],['131000','145500'],['150500','165000'],['170000','184500'],['185500','204000']],lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//YIN//Ibaraki Campus Assistant//EN','CALSCALE:GREGORIAN'];for(const e of events){if(!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||!times[e.period-1])continue;const day=e.date.replace(/-/g,''),t=times[e.period-1];lines.push('BEGIN:VEVENT','UID:'+escape((e.id||e.code)+'-'+day+'-'+e.period)+'@campus.local','DTSTAMP:20260918T000000Z','DTSTART;TZID=Asia/Tokyo:'+day+'T'+t[0],'DTEND;TZID=Asia/Tokyo:'+day+'T'+t[1],'SUMMARY:'+escape(e.name),'END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(line=>{let out='',bytes=0;for(const c of line){const n=new TextEncoder().encode(c).length;if(bytes+n>73){out+='\r\n ';bytes=1;}out+=c;bytes+=n;}return out;}).join('\r\n')+'\r\n';}
 function manualGpa(records){const seen=new Set();let weighted=0,credits=0;for(const r of records){if(!r.id||seen.has(r.id)||!r.name||!(r.credits>0&&r.credits<=100))throw Error('课程代码重复或学分无效');seen.add(r.id);if(r.kind==='SCORED'){if(!Number.isInteger(r.score)||r.score<0||r.score>100)throw Error('分数须为 0–100 的整数');credits+=r.credits;weighted+=(r.score<60?0:(r.score-55)/10)*r.credits;}}return credits?Math.round((weighted/credits+Number.EPSILON)*100)/100:null;}
 const api={norm,leaves,quarter,scope,rule,science,forecast,classify,progress,ics,manualGpa};root.CampusAcademic=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
